# Generated by Django 5.0.6 on 2024-07-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('id_asesor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evaluador', models.CharField(max_length=30)),
                ('id_asesor', models.CharField(max_length=30)),
                ('id_evaluacion', models.CharField(max_length=30)),
                ('fecha_evaluacion', models.DateField()),
                ('visto_asesor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('id_evaluador', models.CharField(max_length=30)),
            ],
        ),
    ]
